import { Injectable, Logger, OnModuleInit } from "@nestjs/common"
import { ConfigService } from "@nestjs/config"
import * as anchor from "@coral-xyz/anchor"
import { AnchorProvider, BN, Program, Wallet } from "@coral-xyz/anchor"
import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
  ComputeBudgetProgram,
} from "@solana/web3.js"
import {
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  getAssociatedTokenAddressSync,
  createTransferInstruction,
  createAssociatedTokenAccountIdempotentInstruction,
} from "@solana/spl-token"
import { TransactionInstruction } from "@solana/web3.js"
import bs58 from "bs58"
import idlJson from "./idl/verity_worldcup.json"
import { StatValidation } from "./txline.service"
import {
  VERITY_WORLDCUP_PROGRAM_ID,
  TXLINE_DEVNET_PROGRAM_ID,
  TXLINE_MAINNET_PROGRAM_ID,
  deriveMarketPda,
  deriveVaultPda,
  derivePositionPda,
  deriveDailyScoresRootsPda,
  randomMarketNonce,
  OP_NONE,
} from "./solana.constants"

export interface CreateMarketPoolParams {
  fixtureId: number
  /** Unique-per-fixture PDA seed. Generated by the caller if omitted. */
  nonce?: number
  statKey: number
  /** Second stat key for relational markets; 0/undefined for single-stat. */
  statKeyB?: number
  /** Arithmetic combine op: 0 none, 1 Add, 2 Subtract. */
  op?: number
  /** Logical combine mode: 0 none, 1 AND, 2 OR (two predicates). */
  logic?: number
  statPeriod: number
  threshold: number
  comparison: number
  /** Predicate B threshold/comparison (logical mode only). */
  thresholdB?: number
  comparisonB?: number
  deadlineUnix: number
  creator: PublicKey
  usdcMint: PublicKey
  feeBps?: number
  creatorFeeShareBps?: number
  lpFeeShareBps?: number
}

export interface CreateMarketPoolResult {
  marketPda: string
  vaultPda: string
  nonce: number
  txSig: string
}

export interface SettleResult {
  txSig: string
  winningSide: number
  voided: boolean
}

/**
 * Keeper-authoritative interactions with the `verity-worldcup` settlement
 * program: creating market pools and settling them via CPI into TxLINE's
 * `validate_stat`. The keeper wallet (SOLANA_KEEPER_PRIVATE_KEY) is a
 * backend-controlled protocol signer, distinct from each user's Circle wallet.
 *
 * Uses a backend keeper wallet as the protocol signer, distinct from each
 * user's custodial Circle wallet.
 */
@Injectable()
export class SolanaService implements OnModuleInit {
  private readonly logger = new Logger(SolanaService.name)
  private connection: Connection
  private keeper: Keypair
  private program: Program
  private txlineProgramId: PublicKey

  constructor(private readonly configService: ConfigService) {}

  onModuleInit() {
    const rpcUrl =
      this.configService.get<string>("SOLANA_RPC_URL") ||
      "https://api.devnet.solana.com"
    this.connection = new Connection(rpcUrl, "confirmed")

    const secret = this.configService.get<string>("SOLANA_KEEPER_PRIVATE_KEY")
    if (!secret) {
      this.logger.warn(
        "SOLANA_KEEPER_PRIVATE_KEY not configured — Solana writes are disabled.",
      )
      return
    }
    this.keeper = Keypair.fromSecretKey(bs58.decode(secret))

    const cluster =
      this.configService.get<string>("SOLANA_CLUSTER") || "devnet"
    this.txlineProgramId =
      cluster === "mainnet"
        ? TXLINE_MAINNET_PROGRAM_ID
        : TXLINE_DEVNET_PROGRAM_ID

    const provider = new AnchorProvider(
      this.connection,
      new Wallet(this.keeper),
      { commitment: "confirmed" },
    )
    anchor.setProvider(provider)
    this.program = new Program(idlJson as anchor.Idl, provider)

    this.logger.log(
      `SolanaService ready (keeper ${this.keeper.publicKey.toBase58()}, txline ${this.txlineProgramId.toBase58()})`,
    )
  }

  get keeperAddress(): string | null {
    return this.keeper?.publicKey.toBase58() ?? null
  }

  private ensureReady() {
    if (!this.program || !this.keeper) {
      throw new Error("SolanaService is not initialized (missing keeper key).")
    }
  }

  /** Create a parimutuel market pool on-chain (keeper as authority). */
  async createMarketPool(
    params: CreateMarketPoolParams,
  ): Promise<CreateMarketPoolResult> {
    this.ensureReady()
    const nonce = params.nonce ?? randomMarketNonce()
    const statKeyB = params.statKeyB ?? 0
    const op = params.op ?? OP_NONE
    const logic = params.logic ?? 0
    const [marketPda] = deriveMarketPda(params.fixtureId, nonce)
    const [vaultPda] = deriveVaultPda(marketPda)

    const txSig = await this.program.methods
      .initMarket(
        new BN(params.fixtureId),
        nonce,
        params.statKey,
        statKeyB,
        op,
        logic,
        params.statPeriod,
        params.threshold,
        params.comparison,
        params.thresholdB ?? 0,
        params.comparisonB ?? 0,
        new BN(params.deadlineUnix),
        params.feeBps ?? 200,
        params.creatorFeeShareBps ?? 2500,
        params.lpFeeShareBps ?? 2500,
      )
      .accounts({
        authority: this.keeper.publicKey,
        creator: params.creator,
        usdcMint: params.usdcMint,
        market: marketPda,
        vault: vaultPda,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      })
      .rpc()

    const combo = logic ? `/${statKeyB} logic${logic}` : op ? `/${statKeyB} op${op}` : ""
    this.logger.log(
      `Created market pool ${marketPda.toBase58()} for fixture ${params.fixtureId} nonce ${nonce} stat ${params.statKey}${combo} (tx ${txSig})`,
    )
    return {
      marketPda: marketPda.toBase58(),
      vaultPda: vaultPda.toBase58(),
      nonce,
      txSig,
    }
  }

  /**
   * String-friendly wrapper around `createMarketPool` that resolves the USDC
   * mint from config and the creator wallet (falling back to the keeper).
   */
  async createMarketPoolFor(params: {
    fixtureId: number
    nonce?: number
    statKey: number
    statKeyB?: number
    op?: number
    logic?: number
    statPeriod: number
    threshold: number
    comparison: number
    thresholdB?: number
    comparisonB?: number
    deadlineUnix: number
    creatorWallet?: string | null
    feeBps?: number
    creatorFeeShareBps?: number
    lpFeeShareBps?: number
  }): Promise<CreateMarketPoolResult> {
    this.ensureReady()
    const mint = this.configService.get<string>("SOLANA_USDC_MINT")
    if (!mint) throw new Error("SOLANA_USDC_MINT not configured.")
    const creator = params.creatorWallet
      ? new PublicKey(params.creatorWallet)
      : this.keeper.publicKey
    return this.createMarketPool({
      fixtureId: params.fixtureId,
      nonce: params.nonce,
      statKey: params.statKey,
      statKeyB: params.statKeyB,
      op: params.op,
      logic: params.logic,
      statPeriod: params.statPeriod,
      threshold: params.threshold,
      comparison: params.comparison,
      thresholdB: params.thresholdB,
      comparisonB: params.comparisonB,
      deadlineUnix: params.deadlineUnix,
      creator,
      usdcMint: new PublicKey(mint),
      feeBps: params.feeBps,
      creatorFeeShareBps: params.creatorFeeShareBps,
      lpFeeShareBps: params.lpFeeShareBps,
    })
  }

  /**
   * Settle a market by CPI-ing into TxLINE `validate_stat` with a fresh proof.
   * Returns the resulting winning side and voided flag read back from chain.
   */
  async settleMarket(
    fixtureId: number,
    nonce: number,
    proof: StatValidation,
    proofB?: StatValidation | null,
  ): Promise<SettleResult> {
    this.ensureReady()
    const [marketPda] = deriveMarketPda(fixtureId, nonce)
    const [dailyScoresPda] = deriveDailyScoresRootsPda(
      proof.epochDay,
      this.txlineProgramId,
    )

    const toNodes = (nodes: StatValidation["statProof"]) =>
      nodes.map((n) => ({ hash: n.hash, isRightSibling: n.isRightSibling }))

    const fixtureSummary = {
      fixtureId: new BN(proof.fixtureSummary.fixtureId),
      updateStats: {
        updateCount: proof.fixtureSummary.updateStats.updateCount,
        minTimestamp: new BN(proof.fixtureSummary.updateStats.minTimestamp),
        maxTimestamp: new BN(proof.fixtureSummary.updateStats.maxTimestamp),
      },
      eventsSubTreeRoot: proof.fixtureSummary.eventsSubTreeRoot,
    }

    // Relational markets combine a second proven stat (winner/spread/totals).
    const statB = proofB
      ? {
          value: proofB.statValue,
          period: proofB.statPeriod,
          eventStatRoot: proofB.eventStatRoot,
          statProof: toNodes(proofB.statProof),
        }
      : null

    const txSig = await this.program.methods
      .settle(
        new BN(proof.ts),
        fixtureSummary,
        toNodes(proof.fixtureProof),
        toNodes(proof.mainTreeProof),
        proof.statValue,
        proof.statPeriod,
        proof.eventStatRoot,
        toNodes(proof.statProof),
        statB,
      )
      .accounts({
        authority: this.keeper.publicKey,
        market: marketPda,
        dailyScoresMerkleRoots: dailyScoresPda,
        txlineProgram: this.txlineProgramId,
      })
      .preInstructions([
        ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
      ])
      .rpc()

    const market = await this.readPoolState(fixtureId, nonce)
    this.logger.log(
      `Settled market ${marketPda.toBase58()} winningSide=${market.winningSide} voided=${market.voided} (tx ${txSig})`,
    )
    return {
      txSig,
      winningSide: market.winningSide,
      voided: market.voided,
    }
  }

  /** Read a wallet's USDC (SPL) balance and native SOL balance. */
  async getWalletBalances(
    walletAddress: string,
  ): Promise<{ usdc: number; sol: number }> {
    const owner = new PublicKey(walletAddress)
    const solLamports = await this.connection.getBalance(owner)
    let usdc = 0
    try {
      const mint = this.configService.get<string>("SOLANA_USDC_MINT")
      if (mint) {
        const ata = getAssociatedTokenAddressSync(new PublicKey(mint), owner)
        const bal = await this.connection.getTokenAccountBalance(ata)
        usdc = bal.value.uiAmount ?? 0
      }
    } catch {
      // No ATA yet -> zero balance.
    }
    return { usdc, sol: solLamports / 1e9 }
  }

  /** Read the on-chain market account state. */
  async readPoolState(fixtureId: number, nonce: number): Promise<any> {
    this.ensureReady()
    const [marketPda] = deriveMarketPda(fixtureId, nonce)
    return (this.program.account as any).market.fetch(marketPda)
  }

  // --- user-signed instruction builders ---------------------------------
  // These return a TransactionInstruction with `user` as the signer; the
  // caller (CircleSolanaWalletService) sets the fee payer and signs via Circle.

  private usdcMint(): PublicKey {
    const mint = this.configService.get<string>("SOLANA_USDC_MINT")
    if (!mint) throw new Error("SOLANA_USDC_MINT not configured.")
    return new PublicKey(mint)
  }

  /** Build a `stake(side, amount)` instruction for a user. */
  async buildStakeInstruction(
    fixtureId: number,
    nonce: number,
    user: PublicKey,
    side: number,
    amountBaseUnits: bigint,
  ): Promise<TransactionInstruction> {
    this.ensureReady()
    const [marketPda] = deriveMarketPda(fixtureId, nonce)
    const [vaultPda] = deriveVaultPda(marketPda)
    const userUsdc = getAssociatedTokenAddressSync(this.usdcMint(), user)

    return this.program.methods
      .stake(side, new BN(amountBaseUnits.toString()))
      .accounts({
        user,
        market: marketPda,
        vault: vaultPda,
        userUsdc,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .instruction()
  }

  /** Build an `add_liquidity(amount)` instruction for a user. */
  async buildAddLiquidityInstruction(
    fixtureId: number,
    nonce: number,
    user: PublicKey,
    amountBaseUnits: bigint,
  ): Promise<TransactionInstruction> {
    this.ensureReady()
    const [marketPda] = deriveMarketPda(fixtureId, nonce)
    const [vaultPda] = deriveVaultPda(marketPda)
    const userUsdc = getAssociatedTokenAddressSync(this.usdcMint(), user)

    return this.program.methods
      .addLiquidity(new BN(amountBaseUnits.toString()))
      .accounts({
        user,
        market: marketPda,
        vault: vaultPda,
        userUsdc,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .instruction()
  }

  /** Build a `claim()` instruction for a user's winning position. */
  async buildClaimInstruction(
    fixtureId: number,
    nonce: number,
    user: PublicKey,
  ): Promise<TransactionInstruction> {
    this.ensureReady()
    const [marketPda] = deriveMarketPda(fixtureId, nonce)
    const [vaultPda] = deriveVaultPda(marketPda)
    const [positionPda] = derivePositionPda(marketPda, user)
    const userUsdc = getAssociatedTokenAddressSync(this.usdcMint(), user)

    return this.program.methods
      .claim()
      .accounts({
        user,
        market: marketPda,
        position: positionPda,
        vault: vaultPda,
        userUsdc,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .instruction()
  }

  /**
   * Build USDC transfer instructions from `sender` to `recipient` (creating the
   * recipient's ATA if needed). The sender's Circle wallet signs + pays.
   */
  buildUsdcTransferInstructions(
    sender: PublicKey,
    recipient: PublicKey,
    amountBaseUnits: bigint,
  ): TransactionInstruction[] {
    const mint = this.usdcMint()
    const senderAta = getAssociatedTokenAddressSync(mint, sender)
    const recipientAta = getAssociatedTokenAddressSync(mint, recipient)
    return [
      createAssociatedTokenAccountIdempotentInstruction(
        sender,
        recipientAta,
        recipient,
        mint,
      ),
      createTransferInstruction(senderAta, recipientAta, sender, amountBaseUnits),
    ]
  }

  programId(): PublicKey {
    return VERITY_WORLDCUP_PROGRAM_ID
  }
}
