import { Injectable, Logger, OnModuleInit } from "@nestjs/common"
import { ConfigService } from "@nestjs/config"
import * as anchor from "@coral-xyz/anchor"
import { AnchorProvider, BN, Program, Wallet } from "@coral-xyz/anchor"
import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
  ComputeBudgetProgram,
} from "@solana/web3.js"
import {
  TOKEN_PROGRAM_ID,
  ASSOCIATED_TOKEN_PROGRAM_ID,
  getAssociatedTokenAddressSync,
  createTransferInstruction,
  createAssociatedTokenAccountIdempotentInstruction,
} from "@solana/spl-token"
import { TransactionInstruction } from "@solana/web3.js"
import bs58 from "bs58"
import idlJson from "./idl/verity_worldcup.json"
import { StatValidation } from "./txline.service"
import {
  VERITY_WORLDCUP_PROGRAM_ID,
  TXLINE_DEVNET_PROGRAM_ID,
  TXLINE_MAINNET_PROGRAM_ID,
  deriveMarketPda,
  deriveVaultPda,
  derivePositionPda,
  deriveDailyScoresRootsPda,
  randomMarketNonce,
  OP_NONE,
} from "./solana.constants"

/** Predicate for one non-default outcome, applied to the shared stat pair. */
export interface OutcomeRuleInput {
  op: number // 0 none, 1 Add, 2 Subtract
  logic: number // 0 none, 1 AND, 2 OR
  threshold: number
  comparison: number // 0 GT, 1 LT, 2 EQ
  thresholdB: number
  comparisonB: number
}

export interface CreateMarketPoolParams {
  fixtureId: number
  /** Unique-per-fixture PDA seed. Generated by the caller if omitted. */
  nonce?: number
  statKey: number
  /** Second stat key shared by all outcome rules; 0/undefined for single-stat. */
  statKeyB?: number
  statPeriod: number
  /** Total outcomes (2..=MAX). Outcome 0 is the default bucket. */
  outcomeCount: number
  /** Predicate per non-default outcome (length outcomeCount - 1). */
  rules: OutcomeRuleInput[]
  deadlineUnix: number
  usdcMint: PublicKey
  feeBps?: number
}

export interface CreateMarketPoolResult {
  marketPda: string
  vaultPda: string
  nonce: number
  txSig: string
}

export interface SettleResult {
  txSig: string
  winningOutcome: number
  voided: boolean
}

/**
 * Keeper-authoritative interactions with the `verity-worldcup` settlement
 * program: creating market pools and settling them via CPI into TxLINE's
 * `validate_stat`. The keeper wallet (SOLANA_KEEPER_PRIVATE_KEY) is a
 * backend-controlled protocol signer, distinct from each user's Circle wallet.
 *
 * Uses a backend keeper wallet as the protocol signer, distinct from each
 * user's custodial Circle wallet.
 */
@Injectable()
export class SolanaService implements OnModuleInit {
  private readonly logger = new Logger(SolanaService.name)
  private connection: Connection
  private keeper: Keypair
  private program: Program
  private txlineProgramId: PublicKey

  constructor(private readonly configService: ConfigService) {}

  onModuleInit() {
    const rpcUrl =
      this.configService.get<string>("SOLANA_RPC_URL") ||
      "https://api.devnet.solana.com"
    this.connection = new Connection(rpcUrl, "confirmed")

    const secret = this.configService.get<string>("SOLANA_KEEPER_PRIVATE_KEY")
    if (!secret) {
      this.logger.warn(
        "SOLANA_KEEPER_PRIVATE_KEY not configured — Solana writes are disabled.",
      )
      return
    }
    this.keeper = Keypair.fromSecretKey(bs58.decode(secret))

    const cluster =
      this.configService.get<string>("SOLANA_CLUSTER") || "devnet"
    this.txlineProgramId =
      cluster === "mainnet"
        ? TXLINE_MAINNET_PROGRAM_ID
        : TXLINE_DEVNET_PROGRAM_ID

    const provider = new AnchorProvider(
      this.connection,
      new Wallet(this.keeper),
      { commitment: "confirmed" },
    )
    anchor.setProvider(provider)
    this.program = new Program(idlJson as anchor.Idl, provider)

    this.logger.log(
      `SolanaService ready (keeper ${this.keeper.publicKey.toBase58()}, txline ${this.txlineProgramId.toBase58()})`,
    )
  }

  get keeperAddress(): string | null {
    return this.keeper?.publicKey.toBase58() ?? null
  }

  private ensureReady() {
    if (!this.program || !this.keeper) {
      throw new Error("SolanaService is not initialized (missing keeper key).")
    }
  }

  /** Create a parimutuel market pool on-chain (keeper as authority). */
  async createMarketPool(
    params: CreateMarketPoolParams,
  ): Promise<CreateMarketPoolResult> {
    this.ensureReady()
    const nonce = params.nonce ?? randomMarketNonce()
    const statKeyB = params.statKeyB ?? 0
    if (params.rules.length !== params.outcomeCount - 1) {
      throw new Error(
        `rules length (${params.rules.length}) must equal outcomeCount-1 (${params.outcomeCount - 1})`,
      )
    }
    const [marketPda] = deriveMarketPda(params.fixtureId, nonce)
    const [vaultPda] = deriveVaultPda(marketPda)

    const txSig = await this.program.methods
      .initMarket(
        new BN(params.fixtureId),
        nonce,
        params.statKey,
        statKeyB,
        params.statPeriod,
        params.outcomeCount,
        params.rules,
        new BN(params.deadlineUnix),
        params.feeBps ?? 200,
      )
      .accounts({
        authority: this.keeper.publicKey,
        usdcMint: params.usdcMint,
        market: marketPda,
        vault: vaultPda,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      })
      .rpc()

    this.logger.log(
      `Created ${params.outcomeCount}-outcome pool ${marketPda.toBase58()} for fixture ${params.fixtureId} nonce ${nonce} stat ${params.statKey}${statKeyB ? `/${statKeyB}` : ""} (tx ${txSig})`,
    )
    return {
      marketPda: marketPda.toBase58(),
      vaultPda: vaultPda.toBase58(),
      nonce,
      txSig,
    }
  }

  /**
   * String-friendly wrapper around `createMarketPool` that resolves the USDC
   * mint from config. Markets are admin/keeper-created (pure parimutuel).
   */
  async createMarketPoolFor(params: {
    fixtureId: number
    nonce?: number
    statKey: number
    statKeyB?: number
    statPeriod: number
    outcomeCount: number
    rules: OutcomeRuleInput[]
    deadlineUnix: number
    feeBps?: number
  }): Promise<CreateMarketPoolResult> {
    this.ensureReady()
    const mint = this.configService.get<string>("SOLANA_USDC_MINT")
    if (!mint) throw new Error("SOLANA_USDC_MINT not configured.")
    return this.createMarketPool({
      fixtureId: params.fixtureId,
      nonce: params.nonce,
      statKey: params.statKey,
      statKeyB: params.statKeyB,
      statPeriod: params.statPeriod,
      outcomeCount: params.outcomeCount,
      rules: params.rules,
      deadlineUnix: params.deadlineUnix,
      usdcMint: new PublicKey(mint),
      feeBps: params.feeBps,
    })
  }

  /**
   * Settle a market by CPI-ing into TxLINE `validate_stat` with a fresh proof.
   * Returns the resulting winning side and voided flag read back from chain.
   */
  async settleMarket(
    fixtureId: number,
    nonce: number,
    proof: StatValidation,
    proofB?: StatValidation | null,
  ): Promise<SettleResult> {
    this.ensureReady()
    const [marketPda] = deriveMarketPda(fixtureId, nonce)
    const [dailyScoresPda] = deriveDailyScoresRootsPda(
      proof.epochDay,
      this.txlineProgramId,
    )

    const toNodes = (nodes: StatValidation["statProof"]) =>
      nodes.map((n) => ({ hash: n.hash, isRightSibling: n.isRightSibling }))

    const fixtureSummary = {
      fixtureId: new BN(proof.fixtureSummary.fixtureId),
      updateStats: {
        updateCount: proof.fixtureSummary.updateStats.updateCount,
        minTimestamp: new BN(proof.fixtureSummary.updateStats.minTimestamp),
        maxTimestamp: new BN(proof.fixtureSummary.updateStats.maxTimestamp),
      },
      eventsSubTreeRoot: proof.fixtureSummary.eventsSubTreeRoot,
    }

    // Relational markets combine a second proven stat (winner/spread/totals).
    const statB = proofB
      ? {
          value: proofB.statValue,
          period: proofB.statPeriod,
          eventStatRoot: proofB.eventStatRoot,
          statProof: toNodes(proofB.statProof),
        }
      : null

    const txSig = await this.program.methods
      .settle(
        new BN(proof.ts),
        fixtureSummary,
        toNodes(proof.fixtureProof),
        toNodes(proof.mainTreeProof),
        proof.statValue,
        proof.statPeriod,
        proof.eventStatRoot,
        toNodes(proof.statProof),
        statB,
      )
      .accounts({
        authority: this.keeper.publicKey,
        market: marketPda,
        dailyScoresMerkleRoots: dailyScoresPda,
        txlineProgram: this.txlineProgramId,
      })
      .preInstructions([
        ComputeBudgetProgram.setComputeUnitLimit({ units: 1_400_000 }),
      ])
      .rpc()

    const market = await this.readPoolState(fixtureId, nonce)
    this.logger.log(
      `Settled market ${marketPda.toBase58()} winningOutcome=${market.winningOutcome} voided=${market.voided} (tx ${txSig})`,
    )
    return {
      txSig,
      winningOutcome: market.winningOutcome,
      voided: market.voided,
    }
  }

  /** Read a wallet's USDC (SPL) balance and native SOL balance. */
  async getWalletBalances(
    walletAddress: string,
  ): Promise<{ usdc: number; sol: number }> {
    const owner = new PublicKey(walletAddress)
    const solLamports = await this.connection.getBalance(owner)
    let usdc = 0
    try {
      const mint = this.configService.get<string>("SOLANA_USDC_MINT")
      if (mint) {
        const ata = getAssociatedTokenAddressSync(new PublicKey(mint), owner)
        const bal = await this.connection.getTokenAccountBalance(ata)
        usdc = bal.value.uiAmount ?? 0
      }
    } catch {
      // No ATA yet -> zero balance.
    }
    return { usdc, sol: solLamports / 1e9 }
  }

  /** Read the on-chain market account state. */
  async readPoolState(fixtureId: number, nonce: number): Promise<any> {
    this.ensureReady()
    const [marketPda] = deriveMarketPda(fixtureId, nonce)
    return (this.program.account as any).market.fetch(marketPda)
  }

  /**
   * Like `readPoolState` but returns `null` when the account is missing or was
   * created by an incompatible (older) program layout, instead of throwing.
   */
  async tryReadPoolState(fixtureId: number, nonce: number): Promise<any | null> {
    try {
      return await this.readPoolState(fixtureId, nonce)
    } catch {
      return null
    }
  }

  /**
   * Read a bettor's claim status for a market from on-chain state. Combines the
   * settled market snapshot (winning outcome + payout pool) with the user's
   * `Position` account to derive exactly what the `claim` instruction would pay,
   * and whether they've already claimed. Returns a plain, UI-friendly shape.
   *
   * `claimableUsdc` is what remains to be claimed: 0 once `claimed` is true, once
   * the position lost, or before the market resolves.
   */
  async readUserPosition(
    fixtureId: number,
    nonce: number,
    owner: PublicKey,
  ): Promise<{
    hasPosition: boolean
    claimed: boolean
    resolved: boolean
    voided: boolean
    winningOutcome: number | null
    claimableUsdc: number
    stakedUsdc: number
  }> {
    this.ensureReady()
    const market = await this.tryReadPoolState(fixtureId, nonce)
    if (!market) {
      return {
        hasPosition: false,
        claimed: false,
        resolved: false,
        voided: false,
        winningOutcome: null,
        claimableUsdc: 0,
        stakedUsdc: 0,
      }
    }

    const [marketPda] = deriveMarketPda(fixtureId, nonce)
    const [positionPda] = derivePositionPda(marketPda, owner)
    let position: any = null
    try {
      position = await (this.program.account as any).position.fetch(positionPda)
    } catch {
      position = null
    }

    const resolved = Boolean(market.resolved)
    const voided = Boolean(market.voided)
    const winningOutcome =
      resolved && !voided ? Number(market.winningOutcome) : null

    if (!position) {
      return {
        hasPosition: false,
        claimed: false,
        resolved,
        voided,
        winningOutcome,
        claimableUsdc: 0,
        stakedUsdc: 0,
      }
    }

    const stakes: bigint[] = (position.stakes as any[]).map((s) =>
      BigInt(s.toString()),
    )
    const stakedBase = stakes.reduce((sum, s) => sum + s, 0n)
    const claimed = Boolean(position.claimed)

    // Mirror the on-chain `claim` payout math (see programs/.../lib.rs::claim).
    let payoutBase = 0n
    if (resolved && !claimed) {
      if (voided) {
        payoutBase = stakedBase
      } else {
        const winningStake = stakes[Number(market.winningOutcome)] ?? 0n
        const winningPool = BigInt(market.winningPool?.toString() ?? "0")
        const distributable = BigInt(market.distributable?.toString() ?? "0")
        payoutBase =
          winningPool > 0n ? (distributable * winningStake) / winningPool : 0n
      }
    }

    return {
      hasPosition: true,
      claimed,
      resolved,
      voided,
      winningOutcome,
      claimableUsdc: Number(payoutBase) / 1e6,
      stakedUsdc: Number(stakedBase) / 1e6,
    }
  }

  // --- user-signed instruction builders ---------------------------------
  // These return a TransactionInstruction with `user` as the signer; the
  // caller (CircleSolanaWalletService) sets the fee payer and signs via Circle.

  private usdcMint(): PublicKey {
    const mint = this.configService.get<string>("SOLANA_USDC_MINT")
    if (!mint) throw new Error("SOLANA_USDC_MINT not configured.")
    return new PublicKey(mint)
  }

  /** Build a `stake(outcome, amount)` instruction for a user. */
  async buildStakeInstruction(
    fixtureId: number,
    nonce: number,
    user: PublicKey,
    outcome: number,
    amountBaseUnits: bigint,
  ): Promise<TransactionInstruction> {
    this.ensureReady()
    const [marketPda] = deriveMarketPda(fixtureId, nonce)
    const [vaultPda] = deriveVaultPda(marketPda)
    const userUsdc = getAssociatedTokenAddressSync(this.usdcMint(), user)

    return this.program.methods
      .stake(outcome, new BN(amountBaseUnits.toString()))
      .accounts({
        user,
        market: marketPda,
        vault: vaultPda,
        userUsdc,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
      })
      .instruction()
  }

  /** Build a `claim()` instruction for a user's winning position. */
  async buildClaimInstruction(
    fixtureId: number,
    nonce: number,
    user: PublicKey,
  ): Promise<TransactionInstruction> {
    this.ensureReady()
    const [marketPda] = deriveMarketPda(fixtureId, nonce)
    const [vaultPda] = deriveVaultPda(marketPda)
    const [positionPda] = derivePositionPda(marketPda, user)
    const userUsdc = getAssociatedTokenAddressSync(this.usdcMint(), user)

    return this.program.methods
      .claim()
      .accounts({
        user,
        market: marketPda,
        position: positionPda,
        vault: vaultPda,
        userUsdc,
        tokenProgram: TOKEN_PROGRAM_ID,
      })
      .instruction()
  }

  /**
   * Build USDC transfer instructions from `sender` to `recipient` (creating the
   * recipient's ATA if needed). The sender's Circle wallet signs + pays.
   */
  buildUsdcTransferInstructions(
    sender: PublicKey,
    recipient: PublicKey,
    amountBaseUnits: bigint,
  ): TransactionInstruction[] {
    const mint = this.usdcMint()
    const senderAta = getAssociatedTokenAddressSync(mint, sender)
    const recipientAta = getAssociatedTokenAddressSync(mint, recipient)
    return [
      createAssociatedTokenAccountIdempotentInstruction(
        sender,
        recipientAta,
        recipient,
        mint,
      ),
      createTransferInstruction(senderAta, recipientAta, sender, amountBaseUnits),
    ]
  }

  programId(): PublicKey {
    return VERITY_WORLDCUP_PROGRAM_ID
  }
}
